# NOTEBOOK PARA PROCESAR BASES DE DATOS DE VENTAS EN MERCADOS DURANTE 2024-2025 (hasta 13-07-2025)

## UNIÓN ENTRE BASES 2024 Y 2025 HASTA 13-07

In [1]:
import pandas as pd

In [2]:
# Ventas 2024
path_ventas_2024 = '/Users/martincarrasco/Desktop/Martín_Carrasco/Reportes/2024/Ventas procesadas/Ventas accesorios-lubricantes-neumaticos-repuestos 2024.csv'
ventas_2024 = pd.read_csv(path_ventas_2024, sep=',', encoding='utf-8')

# Ventas 2025 (hasta 20-07)
path_ventas_2025 = '/Users/martincarrasco/Desktop/Martín_Carrasco/Reportes/2025/Ventas procesadas/ventas accesorios-lubricantes-neumaticos-repuestos 2025 (hasta 03-09).csv'
ventas_2025 = pd.read_csv(path_ventas_2025, sep=',', encoding='utf-8')

In [3]:
ventas_2024_2025 = pd.concat([ventas_2024, ventas_2025], ignore_index=True)
ventas_2024_2025.to_csv('/Users/martincarrasco/Desktop/Martín_Carrasco/Reportes/Interanuales/Ventas procesadas/ventas accesorios-lubricantes-neumaticos-repuestos 2024-2025 (hasta 03-09-2025).csv', index=False, encoding='utf-8')

In [4]:
ventas_2024_2025

,Producto,Mercado,Proveedor,SKU,Marca,Categoría,Subcategoría,Año,Mes,Fecha venta,Seller,Unidades_Vendidas,Ventas,Cancelaciones
0,Carpa Funda Cubre Auto Suv Premium Con F,Accesorios,-,(blanco),TECNOTIENDARR,Accesorios de Exterior,Cobertores,2024,10,2024-10-01,salamandra.plata.pictorico,793,15852070,259870
1,Carpa Funda Cubre Auto Suv Premium Con F,Accesorios,-,(blanco),TECNOTIENDARR,Accesorios de Exterior,Cobertores,2024,9,2024-09-01,salamandra.plata.pictorico,753,15052470,99950
2,Carpa Funda Cubre Auto Suv Premium Con F,Accesorios,-,(blanco),TECNOTIENDARR,Accesorios de Exterior,Cobertores,2024,8,2024-08-01,salamandra.plata.pictorico,673,13949270,273870
3,Carpa Funda Cubre Auto Suv Premium Con F,Accesorios,-,(blanco),TECNOTIENDARR,Accesorios de Exterior,Cobertores,2024,11,2024-11-01,salamandra.plata.pictorico,684,13673160,39980
4,Fundas Cubreasiento B-equip Ecocuero Neg,Accesorios,-,(blanco),B-EQUIP,Accesorios de Interior,Cubre Asientos,2024,8,2024-08-01,secretario.jade.peleon,343,11012599,99877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2400066,Espejo De Maquillaje De Visera De Coche,Repuestos,-,OBEK45956,SHUANG.W,Repuestos de Interior,Viseras,2025,6,2025-06-01,calao.amelocotonado.luminar,2,0,0
2400067,Jgo. Bujías Mopar Original Jeep Grand Ch,Repuestos,-,68303913AA,MOPAR,Encendido,Bujías,2025,6,2025-06-01,ASTARA REPUESTOSEXPRESS,1,0,0
2400068,Barra De Dirección Kyc X5 Y X5 Plus,Repuestos,-,(blanco),KYC,Suspensión y Dirección,Barras y Piezas,2025,2,2025-02-01,ROGU5895488,1,0,0
2400069,Kit Ampolleta Bosch Cola De Pez W5w T10,Repuestos,-,3165141228939,BOSCH,Iluminación,Ampolletas y LEDs,2025,9,2025-09-01,TODOPARTS CL,1,0,0
2400070,Sensor Presión Aire Acondicionado Para C,Repuestos,-,GENLY240607LXY15,GENOVATION,Climatización,Aires Acondicionados,2025,7,2025-07-01,lemming.anacardo.fragil,1,0,0

In [5]:
ventas_2024_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400071 entries, 0 to 2400070
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   Producto           object
 1   Mercado            object
 2   Proveedor          object
 3   SKU                object
 4   Marca              object
 5   Categoría          object
 6   Subcategoría       object
 7   Año                int64
 8   Mes                int64
 9   Fecha venta        object
 10  Seller             object
 11  Unidades_Vendidas  int64
 12  Ventas             int64
 13  Cancelaciones      int64
dtypes: int64(5), object(9)
memory usage: 256.4+ MB

In [6]:
ventas_2024_2025.groupby('Fecha venta')['Ventas'].sum()

Fecha venta
2024-01-01    10659701295
2024-02-01     9332939814
2024-03-01     9195821405
2024-04-01     9455310242
2024-05-01     9043346758
2024-06-01     9144952905
2024-07-01     9905379857
2024-08-01     9815122652
2024-09-01     8894849847
2024-10-01    10405479412
2024-11-01     9893767313
2024-12-01     9579070957
2025-01-01    11802976037
2025-02-01    10477284576
2025-03-01    11917660311
2025-04-01    11180248828
2025-05-01    11331708853
2025-06-01    11868037250
2025-07-01    12290303574
2025-08-01    11811379481
2025-09-01     1672732614
Name: Ventas, dtype: int64

In [7]:
ventas_2024_2025['Mercado'].unique()

array(['Accesorios', 'Lubricantes', 'Neumáticos', 'Repuestos'],
      dtype=object)

In [8]:
ventas_2024_2025['Proveedor'].unique()

array(['-', 'BICIMOTO', 'CUATRO RUEDAS', 'REFAX', 'MANNHEIM', 'ALSACIA',
       'MATSUMOTO', 'NEUMACHILE', 'BODEGA', 'IMASA', 'MEC', 'AUTOMARCO',
       'NORIEGA', 'EMASA', 'IMISA', 'ITALFRENOS', 'GABTEC', 'AUTOTEC'],
      dtype=object)

In [9]:
ventas_2024_2025[ventas_2024_2025['Seller'] == 'REPUESTOS DEL SOL']

,Producto,Mercado,Proveedor,SKU,Marca,Categoría,Subcategoría,Año,Mes,Fecha venta,Seller,Unidades_Vendidas,Ventas,Cancelaciones
499,Tapa Rueda Chevrolet Sail 1.4 2011 2016,Accesorios,-,(blanco),GENÉRICO,Accesorios de Exterior,Tapas de Rueda,2024,3,2024-03-01,REPUESTOS DEL SOL,62,1820480,57980
699,Tapa Rueda Chevrolet Sail 1.4 2011 2016,Accesorios,-,(blanco),CIB,Accesorios de Exterior,Tapas de Rueda,2024,10,2024-10-01,REPUESTOS DEL SOL,71,1490290,20990
715,Tapa Rueda Chevrolet Sail 1.4 2011 2016,Accesorios,-,(blanco),GENÉRICO,Accesorios de Exterior,Tapas de Rueda,2024,2,2024-02-01,REPUESTOS DEL SOL,51,1462230,0
739,Tapa Rueda Chevrolet Sail 1.4 2011 2016,Accesorios,-,(blanco),GENÉRICO,Accesorios de Exterior,Tapas de Rueda,2024,4,2024-04-01,REPUESTOS DEL SOL,50,1440800,0
1075,Tapa Rueda Chevrolet Sail 1.4 2011 2016,Accesorios,-,(blanco),GENÉRICO,Accesorios de Exterior,Tapas de Rueda,2024,1,2024-01-01,REPUESTOS DEL SOL,43,1167570,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2385073,Empaquetadura Culata Para Century 2.2 Jm,Repuestos,ALSACIA,AL091090068,ALS,Motores,Juntas,2025,4,2025-04-01,REPUESTOS DEL SOL,1,4990,0
2385074,Filtro Aceite Para Subaru Forester 2.0 F,Repuestos,ALSACIA,AL071231956,ONNURI,Filtros,Filtros de Aceite,2025,2,2025-02-01,REPUESTOS DEL SOL,1,4990,0
2385084,Piola Acelerador Changan S100 1.0 2007,Repuestos,MANNHEIM,MA0042210021,GENÉRICO,Motores,Cables de Comandos,2025,1,2025-01-01,REPUESTOS DEL SOL,1,4990,0
2385092,Piola Acelerador Changan S200 1.0 2007,Repuestos,MANNHEIM,MA0042210021,GENÉRICO,Motores,Cables de Comandos,2025,1,2025-01-01,REPUESTOS DEL SOL,1,4990,0
2385097,Buje Barra Estabilizadora Chevrolet Spar,Repuestos,REFAX,RX1001920X2,GENÉRICO,Suspensión y Dirección,Bujes de Suspensión,2025,4,2025-04-01,REPUESTOS DEL SOL,1,4990,0